In [95]:
import pandas as aju
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits,load_iris
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold,cross_val_score
import numpy as np

In [11]:
digit = load_digits()

In [17]:
x_train,x_test,y_train,y_test = train_test_split(digit.data,digit.target,test_size = 0.2,random_state = 99)

In [29]:
model = LogisticRegression(C=100)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9805555555555555

In [23]:
rfc = RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9777777777777777

In [25]:
svc = SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.9888888888888889

In [37]:
kf = KFold(n_splits =3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [47]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)
# since the n_splits = 3; 1 to 9 was divided into 3 splits like 0 1 2 | 3 4 5| 6 7 8 
# 2 folds for training and 1 for testing

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [51]:
def model_score(mod,x_train,x_test,y_train,y_test):
    mod.fit(x_train,y_train)
    return mod.score(x_test,y_test)

In [53]:
model_score(model,x_train,x_test,y_train,y_test)

0.9805555555555555

In [55]:
model_score(rfc,x_train,x_test,y_train,y_test)

0.9805555555555555

In [57]:
model_score(svc,x_train,x_test,y_train,y_test)

0.9888888888888889

In [61]:
score_lr = []
score_rfc = []
score_svc = []
for train_index,test_index in kf.split(digit.data):
    x_train,x_test,y_train,y_test = digit.data[train_index],digit.data[test_index],digit.target[train_index],digit.target[test_index]
    score_lr.append(model_score(model,x_train,x_test,y_train,y_test))
    score_rfc.append(model_score(rfc,x_train,x_test,y_train,y_test))
    score_svc.append(model_score(svc,x_train,x_test,y_train,y_test))
    

In [63]:
score_lr

[0.9081803005008348, 0.9382303839732888, 0.8998330550918197]

In [65]:
score_rfc

[0.9465776293823038, 0.9599332220367279, 0.9265442404006677]

In [67]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [73]:
cross_val_score(LogisticRegression(),digit.data,digit.target)

D:\python_anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\python_anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_o

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [79]:
iris = load_iris()

In [97]:
v = cross_val_score(LogisticRegression(),iris.data,iris.target)
print(v,np.average(v))

[0.96666667 1.         0.93333333 0.96666667 1.        ] 0.9733333333333334


D:\python_anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [99]:
s = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
np.average(s)

0.9666666666666668

In [101]:
c = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
np.average(c)

0.96

In [103]:
y = cross_val_score(SVC(),iris.data,iris.target)
np.average(y)

0.9666666666666666